# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-11 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=30)),
                ('sal', models.FloatField()),
                ('eadd', models.CharField(max_length=45)),
            ],
        ),
    ]
